# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, Lint, and Package
      run: |
        npm install
        npm run lint
        npm run package

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: mega-bot
        path: ./build

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'root'
        server: ${{ secrets.SERVER_IP }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: './build/*'
        remote_path: '/root/mega-bot'

    - name: Launch
      uses: fifsky/ssh-action@master
      with:
        command: |
          killall node
          cd mega-bot
          npm install
          npm run prod
        host: ${{ secrets.SERVER_IP }}
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY}}
